#!/usr/bin/env bash
# deploy-devnet.sh — Deploy all 5 MetaShipX contracts to Supernova devnet
# Prerequisites: mxpy + sc-meta installed, PEM wallet at $WALLET_PEM, EGLD on devnet
# Usage: WALLET_PEM=~/wallet.pem bash deploy-devnet.sh
set -euo pipefail

WALLET="${WALLET_PEM:-~/devnet-wallet.pem}"
PROXY="https://devnet-gateway.multiversx.com"
CHAIN="D"
ENV_FILE="frontend/.env.local"
GAS=80000000

echo "🚀 MetaShipX Devnet Deploy (Supernova)"
echo "Wallet: $WALLET"
echo "Proxy:  $PROXY"
echo ""

# Helper: deploy contract and extract address
deploy_contract() {
  local name=$1
  local wasm=$2

  echo "🔨 Deploying $name..."
  local OUT
  OUT=$(mxpy contract deploy \
    --bytecode="$wasm" \
    --pem="$WALLET" \
    --proxy="$PROXY" \
    --chain="$CHAIN" \
    --gas-limit=$GAS \
    --metadata-payable \
    --send \
    --wait-result \
    --recall-nonce 2>&1)

  local ADDR
  ADDR=$(echo "$OUT" | grep -oE 'erd1[a-z0-9]{58}' | tail -1)
  if [ -z "$ADDR" ]; then
    echo "❌ Deploy failed for $name. Output:"
    echo "$OUT"
    exit 1
  fi
  echo "✅ $name deployed: $ADDR"
  echo "$ADDR"
}

# Build all contracts using sc-meta (recommended over mxpy contract build)
echo "🔨 Building contracts with sc-meta..."
for dir in contracts/battleship contracts/nft contracts/staking contracts/marketplace contracts/tournament; do
  echo "  Building $dir..."
  (cd "$dir" && sc-meta all build)
done
echo ""

# Deploy
BATTLESHIP_ADDR=$(deploy_contract "Battleship"  "contracts/battleship/output/battleship.wasm")
NFT_ADDR=$(deploy_contract         "NFT"         "contracts/nft/output/nft.wasm")
STAKING_ADDR=$(deploy_contract     "Staking"     "contracts/staking/output/staking.wasm")
MARKETPLACE_ADDR=$(deploy_contract "Marketplace" "contracts/marketplace/output/marketplace.wasm")
TOURNAMENT_ADDR=$(deploy_contract  "Tournament"  "contracts/tournament/output/tournament.wasm")

# Write .env.local with VITE_ prefix (required by Vite / frontend/src/config.ts)
echo ""
echo "📝 Writing $ENV_FILE..."
mkdir -p frontend
cat > "$ENV_FILE" << EOF
# Auto-generated by deploy-devnet.sh — $(date -u)
VITE_ENV=devnet
VITE_BATTLESHIP_ADDRESS=$BATTLESHIP_ADDR
VITE_NFT_ADDRESS=$NFT_ADDR
VITE_STAKING_ADDRESS=$STAKING_ADDR
VITE_MARKETPLACE_ADDRESS=$MARKETPLACE_ADDR
VITE_TOURNAMENT_ADDRESS=$TOURNAMENT_ADDR
VITE_NETWORK_URL=https://devnet-api.multiversx.com
VITE_CHAIN_ID=D
VITE_BACKEND_URL=http://localhost:3001
VITE_WS_URL=ws://localhost:3001/ws
# WalletConnect v2 project ID — get one at https://cloud.walletconnect.com
VITE_WC_PROJECT_ID=
EOF

# Register NFT collection (requires 0.05 EGLD)
echo ""
echo "🎨 Registering Ship SFT collection on NFT contract..."
mxpy contract call "$NFT_ADDR" \
  --function="registerShipCollection" \
  --value=50000000000000000 \
  --pem="$WALLET" \
  --proxy="$PROXY" \
  --chain="$CHAIN" \
  --gas-limit=60000000 \
  --send \
  --wait-result \
  --recall-nonce

echo ""
echo "✅ Deploy complete!"
echo ""
echo "Contract addresses:"
echo "  Battleship:  $BATTLESHIP_ADDR"
echo "  NFT:         $NFT_ADDR"
echo "  Staking:     $STAKING_ADDR"
echo "  Marketplace: $MARKETPLACE_ADDR"
echo "  Tournament:  $TOURNAMENT_ADDR"
echo ""
echo "Next steps:"
echo "  1. Copy NFT collection ID from contract events and set:"
echo "       VITE_NFT_COLLECTION_ID=SHIP-xxxxxx  in $ENV_FILE"
echo "  2. Add your WalletConnect project ID:"
echo "       VITE_WC_PROJECT_ID=<your_id>  in $ENV_FILE"
echo "  3. Run frontend: cd frontend && npm run dev"
