#!/usr/bin/env bash
# deploy-devnet.sh — Deploy all 4 MetaShipX contracts to devnet
# Prerequisites: mxpy installed, PEM wallet at $WALLET_PEM, EGLD on devnet
# Usage: WALLET_PEM=~/wallet.pem bash deploy-devnet.sh
set -euo pipefail

WALLET="${WALLET_PEM:-~/devnet-wallet.pem}"
PROXY="https://devnet-gateway.multiversx.com"
CHAIN="D"
ENV_FILE="frontend/.env.local"
GAS=80000000

echo "🚀 MetaShipX Devnet Deploy"
echo "Wallet: $WALLET"
echo "Proxy:  $PROXY"
echo ""

# Helper: deploy contract and extract address
deploy_contract() {
  local name=$1
  local wasm=$2
  local metadata=${3:-"0100"}

  echo "🔨 Deploying $name..."
  local OUT
  OUT=$(mxpy contract deploy \
    --bytecode="$wasm" \
    --pem="$WALLET" \
    --proxy="$PROXY" \
    --chain="$CHAIN" \
    --gas-limit=$GAS \
    --metadata-payable \
    --send \
    --wait-result \
    --recall-nonce 2>&1)

  local ADDR
  ADDR=$(echo "$OUT" | grep -oE 'erd1[a-z0-9]{58}' | tail -1)
  if [ -z "$ADDR" ]; then
    echo "❌ Deploy failed for $name. Output:"
    echo "$OUT"
    exit 1
  fi
  echo "✅ $name deployed: $ADDR"
  echo "$ADDR"
}

# Build all contracts
echo "🔨 Building contracts..."
for dir in contracts/battleship contracts/nft contracts/staking contracts/marketplace; do
  echo "  Building $dir..."
  (cd "$dir" && mxpy contract build --no-wasm-opt 2>/dev/null || mxpy contract build)
done
echo ""

# Deploy
BATTLESHIP_ADDR=$(deploy_contract "Battleship" "contracts/battleship/output/battleship.wasm")
NFT_ADDR=$(deploy_contract "NFT" "contracts/nft/output/nft.wasm")
STAKING_ADDR=$(deploy_contract "Staking" "contracts/staking/output/staking.wasm")
MARKETPLACE_ADDR=$(deploy_contract "Marketplace" "contracts/marketplace/output/marketplace.wasm")

# Write .env
echo ""
echo "📝 Writing $ENV_FILE..."
mkdir -p frontend
cat > "$ENV_FILE" << EOF
# Auto-generated by deploy-devnet.sh — $(date -u)
VITE_ENV=devnet
REACT_APP_BATTLESHIP_ADDRESS=$BATTLESHIP_ADDR
REACT_APP_NFT_ADDRESS=$NFT_ADDR
REACT_APP_STAKING_ADDRESS=$STAKING_ADDR
REACT_APP_MARKETPLACE_ADDRESS=$MARKETPLACE_ADDR
REACT_APP_NETWORK_URL=https://devnet-api.multiversx.com
REACT_APP_CHAIN_ID=D
REACT_APP_BACKEND_URL=http://localhost:3001
REACT_APP_WS_URL=ws://localhost:3001/ws
EOF

# Register NFT collection (requires 0.05 EGLD)
echo ""
echo "🎨 Registering Ship SFT collection on NFT contract..."
mxpy contract call "$NFT_ADDR" \
  --function="registerShipCollection" \
  --value=50000000000000000 \
  --pem="$WALLET" \
  --proxy="$PROXY" \
  --chain="$CHAIN" \
  --gas-limit=60000000 \
  --send \
  --wait-result \
  --recall-nonce

echo ""
echo "✅ Deploy complete!"
echo ""
echo "Contract addresses:"
echo "  Battleship:  $BATTLESHIP_ADDR"
echo "  NFT:         $NFT_ADDR"
echo "  Staking:     $STAKING_ADDR"
echo "  Marketplace: $MARKETPLACE_ADDR"
echo ""
echo "Next: copy NFT collection ID from contract events and set:"
echo "  REACT_APP_NFT_COLLECTION_ID=SHIP-xxxxxx in $ENV_FILE"
echo ""
echo "🚀 Run frontend: cd frontend && npm run dev"
