[package]
name = "staking"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
mx-sdk-debug = ["multiversx-sc-scenario/debug"]

[dependencies.multiversx-sc]
version = "0.45.0"
features = ["esdt"]

[dependencies.multiversx-sc-modules]
version = "0.45.0"

[dev-dependencies.multiversx-sc-scenario]
version = "0.45.0"

[dev-dependencies.multiversx-sc-scenario-format]
version = "0.45.0"
