#!/usr/bin/env bash
# ============================================================
# MetaShipX — Unified Deploy Script
# Works for both devnet and mainnet.
# Usage:
#   CHAIN=devnet  PROXY_URL=https://devnet-api.multiversx.com DEPLOYER_PEM=~/wallet.pem ./scripts/mainnet-deploy.sh
#   CHAIN=mainnet PROXY_URL=https://api.multiversx.com        DEPLOYER_PEM=~/wallet.pem ./scripts/mainnet-deploy.sh
# ============================================================
set -euo pipefail

# ── 1. ENV VALIDATION ────────────────────────────────────────────────────────
for var in DEPLOYER_PEM CHAIN PROXY_URL; do
  if [[ -z "${!var:-}" ]]; then
    echo "❌  ERROR: \$${var} is not set." >&2; exit 1
  fi
done

if [[ "$CHAIN" != "mainnet" && "$CHAIN" != "devnet" && "$CHAIN" != "testnet" ]]; then
  echo "❌  ERROR: CHAIN must be mainnet | devnet | testnet. Got: '$CHAIN'" >&2; exit 1
fi
if [[ ! -f "$DEPLOYER_PEM" ]]; then
  echo "❌  ERROR: PEM file not found: $DEPLOYER_PEM" >&2; exit 1
fi

DEPLOYER_ADDR=$(mxpy wallet convert --infile "$DEPLOYER_PEM" --outformat address 2>/dev/null || echo 'unknown')
echo ""
echo "🚀  MetaShipX Deploy"
echo "   Chain    : $CHAIN"
echo "   Proxy    : $PROXY_URL"
echo "   Deployer : $DEPLOYER_ADDR"
echo ""

if [[ "$CHAIN" == "mainnet" ]]; then
  echo "⚠️  MAINNET DEPLOY — this uses real EGLD. Ctrl+C to abort."
  read -r -p "   Type 'deploy mainnet' to confirm: " confirm
  [[ "$confirm" == "deploy mainnet" ]] || { echo "Aborted."; exit 0; }
else
  read -r -p "Continue devnet deploy? [y/N] " confirm
  [[ "$confirm" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 0; }
fi

# ── 2. BUILD ─────────────────────────────────────────────────────────────────
echo ""
echo "📦  Building all contracts..."
for contract in nft staking marketplace battleship tournament; do
  echo "   Building $contract..."
  (cd "contracts/$contract" && sc-meta all build --release) \
    || { echo "❌  Build failed: $contract"; exit 1; }
  echo "   ✅ $contract built."
done

# ── 3. DEPLOY (ordered by dependency) ────────────────────────────────────────
ADDR_FILE="contracts/deployed-${CHAIN}.json"
echo '{}' > "$ADDR_FILE"

deploy_contract() {
  local name="$1"
  local extra_args="${2:-}"
  local wasm="contracts/${name}/output/${name}.wasm"
  [[ -f "$wasm" ]] || { echo "❌  WASM not found: $wasm"; exit 1; }

  echo ""
  echo "🔗  Deploying $name..."
  local out
  # shellcheck disable=SC2086
  out=$(mxpy contract deploy \
    --bytecode "$wasm" \
    --pem "$DEPLOYER_PEM" \
    --proxy "$PROXY_URL" \
    --chain "$CHAIN" \
    --gas-limit 150000000 \
    --send \
    $extra_args 2>&1)

  local addr
  addr=$(echo "$out" | grep -oE 'erd1[0-9a-z]{58}' | head -1)
  if [[ -z "$addr" ]]; then
    echo "❌  Deploy failed for $name:"
    echo "$out"
    exit 1
  fi

  echo "   ✅ $name → $addr"
  python3 - <<PYEOF
import json
with open('$ADDR_FILE') as f: d = json.load(f)
d['$name'] = '$addr'
with open('$ADDR_FILE', 'w') as f: json.dump(d, f, indent=2)
PYEOF
  echo "$addr"
}

NFT_ADDR=$(deploy_contract "nft")
STAKING_ADDR=$(deploy_contract "staking")
MARKETPLACE_ADDR=$(deploy_contract "marketplace")
BATTLESHIP_ADDR=$(deploy_contract "battleship")
TOURNAMENT_ADDR=$(deploy_contract "tournament")

# ── 4. GENERATE FRONTEND ENV ─────────────────────────────────────────────────
ENV_FILE="frontend/.env.${CHAIN}.local"
cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/mainnet-deploy.sh — DO NOT EDIT MANUALLY
# Chain: $CHAIN | $(date -u '+%Y-%m-%dT%H:%M:%SZ')
VITE_ENV=${CHAIN}
VITE_API_URL=${PROXY_URL}
VITE_BATTLESHIP_ADDRESS=${BATTLESHIP_ADDR}
VITE_NFT_ADDRESS=${NFT_ADDR}
VITE_STAKING_ADDRESS=${STAKING_ADDR}
VITE_MARKETPLACE_ADDRESS=${MARKETPLACE_ADDR}
VITE_TOURNAMENT_ADDRESS=${TOURNAMENT_ADDR}
EOF
echo ""
echo "📝  Frontend env written → $ENV_FILE"

# ── 5. SMOKE TESTS ───────────────────────────────────────────────────────────
echo ""
echo "🔍  Smoke testing read endpoints..."
mxpy contract query "$STAKING_ADDR"    --function getTotalStaked --proxy "$PROXY_URL" \
  && echo "   ✅ staking.getTotalStaked OK" \
  || echo "   ⚠️  staking.getTotalStaked FAILED (non-fatal)"

mxpy contract query "$STAKING_ADDR"    --function getRewardPool  --proxy "$PROXY_URL" \
  && echo "   ✅ staking.getRewardPool OK" \
  || echo "   ⚠️  staking.getRewardPool FAILED (non-fatal)"

# ── 6. REWARD POOL SAFETY CHECK ──────────────────────────────────────────────
RAW_POOL=$(mxpy contract query "$STAKING_ADDR" --function getRewardPool --proxy "$PROXY_URL" 2>/dev/null \
  | grep -oE '[0-9]+' | head -1 || echo '0')
MIN_POOL=1000000000000000000  # 1 EGLD in attoEGLD
if [[ "${RAW_POOL:-0}" -lt "$MIN_POOL" ]]; then
  echo ""
  echo "⚠️  WARNING: Reward pool < 1 EGLD!"
  echo "   Fund it before launch: mxpy contract call $STAKING_ADDR --function fundRewardPool --value <amount>"
fi

# ── 7. SUMMARY ───────────────────────────────────────────────────────────────
echo ""
echo "✅  Deploy complete!"
echo "   Addresses : $ADDR_FILE"
echo "   Frontend  : $ENV_FILE"
echo ""
cat "$ADDR_FILE"
